[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "MARL"
authors = [{name = "Qiong", email = "subaru6725@hotmail.com"}]
dynamic = ["version", "description"]
